import { FACTS, ALGO } from '../facts.js';

const trafficReroute = `Yes — every ${FACTS.rerouteIntervalSec}s if the gain is at least max(${FACTS.rerouteMinGainSec}s, ${FACTS.rerouteMinGainPct}% of what remains)`;
const closureOnly = 'Only when the remaining route crosses a closed road';
const noStep = 'No — it runs instantly';
const yesStep = 'Yes — <kbd>Step</kbd> settles one intersection at a time';
const hFormula = 'h(node) = straight-line distance to drop-off ÷ graph.maxSpeed × graph.heuristicScale';

/** Knowledge articles about the route-finding algorithms. */
export const ARTICLES = [
  {
    id: 'choose-algorithm',
    title: 'Which algorithm should I choose?',
    category: 'Algorithms',
    summary: 'A practical guide to the five route-finding cards and what changes when you pick one.',
    questions: [
      'What algorithms are available? Which algo should I select?',
      'How does it behave when an algorithm is chosen?',
    ],
    blocks: [
      { type: 'p', html: `Each card chooses how ShortestBite searches from the pickup pin to the drop-off pin. The pins stay exactly where you put them; changing cards clears the old search/rider output and the next <strong>Find route</strong> or <kbd>Step</kbd> uses the selected algorithm.` },
      { type: 'table', head: ['Card name', 'Technical name', 'Finds fastest route?', 'Uses traffic?', 'How much it searches', 'Step view?', 'Reroutes on traffic?', 'Best for'], rows: [
        [ALGO.bfs.name, ALGO.bfs.tech, 'No — it finds fewest intersections', 'No, except closures are blocked', 'Wide rings by hop count', yesStep, closureOnly, 'Seeing why “shortest-looking” is not always fastest'],
        [ALGO.dijkstra.name, ALGO.dijkstra.tech, 'Yes', 'Yes', 'Thorough ripple by travel time', yesStep, trafficReroute, 'The reference answer when you want certainty'],
        [ALGO.astar.name, ALGO.astar.tech, 'Yes', 'Yes', 'Usually much narrower, aimed at the drop-off', yesStep, trafficReroute, 'Everyday use: fast search with the same answer as Dijkstra'],
        [ALGO['astar-overestimate'].name, ALGO['astar-overestimate'].tech, 'Not always', 'Yes', 'The thinnest, most eager search', yesStep, trafficReroute, 'Demonstrating how a greedy guess can be wrong'],
        [ALGO.bidirectional.name, ALGO.bidirectional.tech, 'Yes', 'Yes', 'Two travel-time ripples, one from each end', noStep, trafficReroute, 'A fast exact one-shot result without step-by-step animation'],
      ] },
      { type: 'diagram', id: 'search-shapes' },
      { type: 'h', text: 'If you want…' },
      { type: 'list', items: [
        `The best default, pick <strong>${ALGO.astar.name}</strong>.`,
        `The most transparent “prove it” answer, pick <strong>${ALGO.dijkstra.name}</strong>.`,
        `A lesson in why counting turns is misleading, pick <strong>${ALGO.bfs.name}</strong>.`,
        `The fewest explored intersections, with a risk of a slower route, pick <strong>${ALGO['astar-overestimate'].name}</strong>.`,
        `An exact result that runs in one go, pick <strong>${ALGO.bidirectional.name}</strong>.`,
      ] },
      { type: 'h', text: 'What happens when you choose a card' },
      { type: 'steps', items: [
        'The app keeps your pickup and drop-off pins in place.',
        'It clears the previous search colours, result card, rider, race board, route directions and reroute monitor output.',
        `The explanation under the cards changes to that card’s <strong>see</strong> behaviour: for example, ${ALGO.astar.name} says the search stretches toward the drop-off, while ${ALGO.bidirectional.name} says it shows the finished result instead of a spreading step view.`,
        'When you press <strong>Find route</strong>, the search starts from the pickup. In race mode, both selected algorithms plan from the same pins before the riders start.',
        `When you press <kbd>Step</kbd>, BFS, Dijkstra, A* and sloppy A* settle one intersection per click. ${ALGO.bidirectional.name} has no step generator, so <kbd>Step</kbd> runs it instantly.`,
      ] },
      { type: 'callout', tone: 'tip', html: `For most experiments, use <strong>${ALGO.astar.name}</strong> first, then race it against <strong>${ALGO.dijkstra.name}</strong>. They should predict the same fastest route, but A* usually checks fewer intersections.` },
      { type: 'tryit', scenario: 'race-dijkstra-astar', label: `Race ${ALGO.dijkstra.name} vs ${ALGO.astar.name}` },
    ],
    tryIt: 'race-dijkstra-astar',
    related: ['bfs', 'dijkstra', 'astar', 'astar-overestimate', 'bidirectional'],
  },
  {
    id: 'bfs',
    title: ALGO.bfs.name,
    category: 'Algorithms',
    summary: 'Breadth-first search counts intersections, ignores road speed and traffic, and reports the real travel time of the hop-shortest route it found.',
    questions: [
      'What exactly does moving A → B denote when a particular algo is selected?',
      'What if there is traffic?',
      'What does Step do?',
    ],
    blocks: [
      { type: 'h', text: 'The idea in one sentence' },
      { type: 'p', html: `${ALGO.bfs.name} treats every road segment as one equal move, so it finds the route with the fewest intersections, not the fastest delivery.` },
      { type: 'h', text: 'How it works' },
      { type: 'steps', items: [
        'Create a FIFO queue and put the pickup node in it with hop count 0.',
        'Pop the oldest queued node; that node is now settled, and <kbd>Step</kbd> shows it as the next checked intersection.',
        'If the settled node is the drop-off, stop immediately.',
        'Otherwise, scan its outgoing roads. Closed roads are skipped; open roads lead to neighbours.',
        'The first time a neighbour is seen, remember the edge that reached it, set its hop count to current hops + 1, and push it to the back of the queue.',
        'After stopping, rebuild the path from the remembered edges. The displayed cost is then the real travel time of that hop-shortest path using each edge’s length ÷ speed, with no traffic factor.',
      ] },
      { type: 'formula', html: 'priority = hop count; queue = first in, first out' },
      { type: 'trace', id: 'bfs-demo' },
      { type: 'h', text: 'What you’ll see on the map' },
      { type: 'p', html: 'The search spreads in even rings of intersections. It does not lean toward faster arterial roads, quieter streets, or the drop-off; it only cares how many road segments have been crossed.' },
      { type: 'callout', tone: 'why', html: 'BFS can be perfect on an unweighted maze where every move has the same cost. In this app, road segments have different lengths and speeds, so the first route with the fewest hops can easily take longer than a route with more segments.' },
      { type: 'h', text: 'Guarantee' },
      { type: 'p', html: 'It guarantees the fewest-road-segments route among reachable open roads. It does <em>not</em> guarantee the fastest route, and it does not use traffic while choosing nodes.' },
      { type: 'h', text: 'Trade-offs' },
      { type: 'list', items: [
        'Simple and predictable: the frontier is just a queue.',
        'Good for comparing “fewest turns” against fastest-time algorithms.',
        'Misleading for delivery time because a long fast road and a short slow lane both count as one hop.',
        `While riding, it reroutes for closures only. Traffic-only checks are skipped for BFS, so changing congestion will not trigger the ${FACTS.rerouteIntervalSec}s improvement test.`,
      ] },
      { type: 'tryit', scenario: 'race-bfs-dijkstra', label: `Race ${ALGO.bfs.name} vs ${ALGO.dijkstra.name}` },
    ],
    tryIt: 'race-bfs-dijkstra',
    related: ['choose-algorithm', 'dijkstra', 'edge-cost'],
  },
  {
    id: 'dijkstra',
    title: ALGO.dijkstra.name,
    category: 'Algorithms',
    summary: 'Dijkstra settles intersections in increasing predicted travel time, so the first time it reaches the drop-off the route is optimal.',
    questions: [
      'When the graph is being calculated, what’s the criteria to choose a node?',
      'Why are so many unnecessary nodes selected even when that path is not chosen?',
      'What’s the difference between predicted time and actual trip time?',
    ],
    blocks: [
      { type: 'h', text: 'The idea in one sentence' },
      { type: 'p', html: `${ALGO.dijkstra.name} always expands the not-yet-checked intersection with the smallest known travel time from the pickup.` },
      { type: 'h', text: 'How it works' },
      { type: 'steps', items: [
        'Set every node’s best known time to infinity, then set the pickup to 0.',
        'Push the pickup into a min-heap priority queue with priority 0.',
        'Pop the lowest-priority heap entry. If it is a stale duplicate with a worse time than the saved best time, ignore it.',
        'Otherwise, settle that node. In step view, this is the intersection that turns into the next checked node.',
        'If the settled node is the drop-off, stop: no remaining heap entry can beat it.',
        'For each outgoing road, compute its travel-time cost with <a data-kb="edge-cost">edge cost</a>. Closed roads return infinity and are skipped.',
        'If going through the settled node improves a neighbour’s best known time, remember that edge and push the new time into the heap.',
      ] },
      { type: 'formula', html: 'f(node) = g(node)' },
      { type: 'p', html: 'Here, <code>g</code> is the best travel time found so far from pickup to that intersection. With traffic on, each road cost is length ÷ (speed × traffic factor).' },
      { type: 'trace', id: 'dijkstra-demo' },
      { type: 'h', text: 'What you’ll see on the map' },
      { type: 'p', html: 'The checked area swells outward like a travel-time ripple. It may inspect roads that are nowhere near the final route because, until the drop-off is settled, those roads still might lead to a faster path.' },
      { type: 'h', text: 'Guarantee' },
      { type: 'callout', tone: 'why', html: 'Dijkstra is exact because all usable road costs are non-negative. The heap always pops the smallest unfinished travel time, so once a node is settled, no later route can make it cheaper.' },
      { type: 'h', text: 'Trade-offs' },
      { type: 'list', items: [
        'Best when you want the clearest guaranteed-fastest baseline.',
        'Usually explores more intersections than A* because it has no sense of direction.',
        `Uses live traffic costs and, while riding, can reroute every ${FACTS.rerouteIntervalSec}s if a new route saves enough time.`,
        'Predicted time is the planned route cost at search time; actual trip time can differ later if traffic or closures change during the ride.',
      ] },
      { type: 'tryit', scenario: 'race-dijkstra-astar', label: `Race ${ALGO.dijkstra.name} vs ${ALGO.astar.name}` },
    ],
    tryIt: 'race-dijkstra-astar',
    related: ['choose-algorithm', 'astar', 'priority-queue', 'why-extra-nodes'],
  },
  {
    id: 'astar',
    title: ALGO.astar.name,
    category: 'Algorithms',
    summary: 'A* adds a safe straight-line estimate to Dijkstra’s known cost, usually finding the same fastest route after much less searching.',
    questions: [
      'When the graph is being calculated, what’s the criteria to choose a node?',
      'Why are so many unnecessary nodes selected even when that path is not chosen?',
    ],
    blocks: [
      { type: 'h', text: 'The idea in one sentence' },
      { type: 'p', html: `${ALGO.astar.name} is Dijkstra with a compass: it still respects real travel time, but it prefers nodes that also look closer to the drop-off.` },
      { type: 'h', text: 'How it works' },
      { type: 'steps', items: [
        'Build a heuristic function for the drop-off: straight-line distance divided by the fastest graph speed, then multiplied by graph.heuristicScale.',
        'Set the pickup’s known travel time <code>g</code> to 0 and push it into a min-heap with priority <code>h(pickup)</code>.',
        'Pop the lowest-priority heap entry. If that node was already settled from a better duplicate, skip it.',
        'Settle the node, record it for the map and inspector, and stop if it is the drop-off.',
        'For each outgoing open road, compute the same edge cost Dijkstra uses.',
        'If the new <code>g</code> improves a neighbour, remember the edge and push priority <code>g + h</code> into the heap.',
      ] },
      { type: 'formula', html: `f(node) = g(node) + h(node)<br>${hFormula}` },
      { type: 'p', html: `On the realistic map, the heuristic scale comes from <code>FACTS.osmHeuristicScale</code> (${FACTS.osmHeuristicScale}) to keep the estimate conservative for OSM geometry.` },
      { type: 'trace', id: 'astar-demo' },
      { type: 'h', text: 'What you’ll see on the map' },
      { type: 'p', html: 'The checked nodes usually form an oval or beam toward the drop-off instead of a full ripple. Some side roads still get checked when their known travel time plus estimate is competitive.' },
      { type: 'h', text: 'Guarantee' },
      { type: 'callout', tone: 'why', html: 'A* stays exact here because its heuristic never overestimates the remaining travel time: straight-line distance is no longer than any road path, graph.maxSpeed is at least as fast as any road, traffic factors are at most 1 so traffic can only make roads slower, and graph.heuristicScale is kept conservative.' },
      { type: 'h', text: 'Trade-offs' },
      { type: 'list', items: [
        'Usually returns the same route as Dijkstra after settling fewer nodes.',
        'The result is still traffic-aware because <code>g</code> uses the real edge-cost function.',
        'The map can look less “complete” than Dijkstra because A* safely avoids many directions that cannot win.',
        `Like Dijkstra, it can reroute on closures immediately and on traffic checks every ${FACTS.rerouteIntervalSec}s when the saving clears the threshold.`,
      ] },
      { type: 'tryit', scenario: 'race-dijkstra-astar', label: `Try ${ALGO.astar.name} against ${ALGO.dijkstra.name}` },
    ],
    tryIt: 'race-dijkstra-astar',
    related: ['choose-algorithm', 'dijkstra', 'astar-overestimate', 'priority-queue'],
  },
  {
    id: 'astar-overestimate',
    title: ALGO['astar-overestimate'].name,
    category: 'Algorithms',
    summary: `Sloppy A* multiplies the safe heuristic by ${FACTS.overestimateFactor}, so it searches aggressively but can miss the fastest route.`,
    questions: [
      'Why does “Fast but sloppy” sometimes give a slower route?',
    ],
    blocks: [
      { type: 'h', text: 'The idea in one sentence' },
      { type: 'p', html: `${ALGO['astar-overestimate'].name} is A* with its compass turned up too high: it often searches less, but it can stop on a route that is not truly fastest.` },
      { type: 'h', text: 'How it works' },
      { type: 'steps', items: [
        'Use the same graph, edge costs and straight-line heuristic as normal A*.',
        `Multiply every heuristic value by <code>FACTS.overestimateFactor</code> (${FACTS.overestimateFactor}) before putting it in the heap priority.`,
        'Pop the node with the smallest inflated <code>g + h</code> priority.',
        'Skip nodes already settled; settle the popped node and stop as soon as the drop-off is settled.',
        'Relax outgoing open roads with the real traffic-aware edge cost, then push improved neighbours with the inflated priority.',
      ] },
      { type: 'formula', html: `f(node) = g(node) + FACTS.overestimateFactor × h(node)<br>FACTS.overestimateFactor = ${FACTS.overestimateFactor}` },
      { type: 'h', text: 'What you’ll see on the map' },
      { type: 'p', html: 'The search often becomes a thin streak toward the drop-off. It may look impressively decisive, but the final predicted time is the number to trust.' },
      { type: 'h', text: 'Guarantee' },
      { type: 'callout', tone: 'warn', html: `Multiplying by ${FACTS.overestimateFactor} breaks the key A* promise. The estimate can become larger than the true remaining travel time, so the algorithm may settle the drop-off before it has explored a slightly indirect but faster road.` },
      { type: 'p', html: 'That is why this card can return a slower route even though it still uses traffic-aware edge costs. The mistake is not in measuring roads; it is in trusting the remaining-distance guess too strongly.' },
      { type: 'h', text: 'Trade-offs' },
      { type: 'list', items: [
        'Often settles the fewest intersections.',
        'Useful for showing the speed-versus-correctness trade-off.',
        'Can lose a race or show a worse predicted time than Dijkstra/A* on the same pins.',
        `Still reroutes like other weighted algorithms: closures immediately, traffic improvements on the ${FACTS.rerouteIntervalSec}s check cadence.`,
      ] },
      { type: 'tryit', scenario: 'race-sloppy', label: `Try ${ALGO['astar-overestimate'].name}` },
    ],
    tryIt: 'race-sloppy',
    related: ['choose-algorithm', 'astar', 'dijkstra'],
  },
  {
    id: 'bidirectional',
    title: ALGO.bidirectional.name,
    category: 'Algorithms',
    summary: 'Bidirectional Dijkstra runs two exact travel-time searches, one from each end, and stops only when their lower bounds prove the best meeting path cannot be improved.',
    questions: [
      'What does Step do?',
      'When the graph is being calculated, what’s the criteria to choose a node?',
    ],
    blocks: [
      { type: 'h', text: 'The idea in one sentence' },
      { type: 'p', html: `${ALGO.bidirectional.name} runs Dijkstra from the pickup and from the drop-off at the same time, then stitches the best meeting point into one route.` },
      { type: 'h', text: 'How it works' },
      { type: 'steps', items: [
        'Create two min-heaps: the forward heap starts at the pickup with cost 0, and the backward heap starts at the drop-off with cost 0.',
        'Keep forward and backward best-time arrays, remembered edges and settled sets.',
        'Before each pair of steps, look at the two heap tops. If <code>topForward + topBackward >= bestMeetingCost</code>, stop because no unfinished pair of frontiers can improve the best route already found.',
        'Pop and settle one forward node, relaxing outgoing roads with the shared edge-cost function.',
        'If a forward relaxation or settled node touches a node already settled by the backward search, update the best meeting cost and meeting node.',
        'Then pop and settle one backward node, relaxing incoming roads as reverse moves and updating the best meeting cost the same way.',
        'If no meeting node was found, there is no route. Otherwise, stitch pickup → meeting from forward edges and meeting → drop-off from backward edges.',
      ] },
      { type: 'formula', html: 'forward priority = gF(node); backward priority = gB(node)<br>stop when heapF.peek() + heapB.peek() >= best' },
      { type: 'h', text: 'What you’ll see on the map' },
      { type: 'p', html: 'This card has no step generator, so the app runs it instantly and shows the finished route and stats. The card text says you will see the final result rather than two animated frontiers.' },
      { type: 'h', text: 'Guarantee' },
      { type: 'callout', tone: 'why', html: 'The search is exact for the same reason Dijkstra is exact on each side, plus the stopping rule is a proof rather than a first-touch shortcut. It does not stop merely when the frontiers meet; it stops only when the two unfinished heap minima cannot add up to anything cheaper than the best full path already discovered.' },
      { type: 'h', text: 'Trade-offs' },
      { type: 'list', items: [
        'Usually covers less ground than one full Dijkstra ripple on large maps.',
        'Still uses live traffic and closures because both directions call the same edge-cost function.',
        'No <kbd>Step</kbd> animation or node-inspector trace is available for its interleaved two-frontier search.',
        `During a ride, it reroutes on the same weighted-algorithm rules: closures immediately, traffic checks every ${FACTS.rerouteIntervalSec}s when the saving is big enough.`,
      ] },
      { type: 'tryit', scenario: 'bidirectional', label: `Try ${ALGO.bidirectional.name}` },
    ],
    tryIt: 'bidirectional',
    related: ['choose-algorithm', 'dijkstra', 'priority-queue'],
  },
];
