import { FACTS, ALGO, STATS } from '../facts.js';

/** Articles explaining how search chooses intersections and how to inspect those choices. */
export const ARTICLES = [
  {
    id: 'priority-queue',
    title: 'Why the priority queue chooses that intersection',
    category: 'How search decides',
    summary: 'Frontier, settled and unseen intersections, plus the g, h and f scores that decide the next step.',
    questions: [
      'When the graph is being calculated, what\'s the criteria to choose a node?',
      'Why was a node selected?',
    ],
    blocks: [
      { type: 'p', html: 'Search keeps every intersection in one of three states: <strong>unseen</strong>, <strong>frontier</strong>, or <strong>settled</strong>. Unseen means the algorithm has not reached it yet. Frontier means it has a known candidate route. Settled means it has been chosen as the best remaining candidate, so its outgoing roads can be relaxed.' },
      { type: 'diagram', id: 'demo-graph' },
      { type: 'h', text: 'The three scores' },
      { type: 'list', items: [
        '<code>g</code> is cost so far: the predicted time from pickup to this intersection.',
        '<code>h</code> is the estimate from this intersection to the drop-off. For Dijkstra it is <code>0</code>; for A* it is straight-line time using the fastest possible road speed.',
        '<code>f</code> is the priority stored in the queue. Dijkstra uses <code>f = g</code>; A* uses <code>f = g + h</code>.',
      ] },
      { type: 'formula', html: 'A* priority: f = g + h' },
      { type: 'h', text: 'The loop' },
      { type: 'steps', items: [
        'Put the pickup in the frontier with priority <code>0</code>.',
        'Pop the frontier entry with the lowest <code>f</code>. That is the intersection selected now.',
        'Settle it, shown by the blue to violet search colouring on the map.',
        'Relax each open outgoing road: if going through this intersection gives a cheaper <code>g</code> for a neighbour, update that neighbour and record its <code>parent</code> road.',
        'Repeat until the drop-off is settled, then follow the parent links backward to draw the final route.',
      ] },
      { type: 'callout', tone: 'why', html: 'The selected intersection is not chosen because it looks visually closest on the map. It is chosen because it currently has the smallest priority among all waiting frontier intersections.' },
      { type: 'trace', id: 'dijkstra-demo' },
      { type: 'trace', id: 'astar-demo' },
      { type: 'h', text: 'What happens when a cheaper route is found later?' },
      { type: 'p', html: 'The heap uses lazy deletion. Instead of searching inside the heap to remove an older, worse entry, the algorithm pushes a fresh entry with the better priority. When the stale entry eventually pops, Dijkstra skips it if its priority is worse than the official <code>g</code>; A* skips duplicates for already settled intersections.' },
      { type: 'h', text: 'Ties' },
      { type: 'p', html: 'If two frontier entries have the same priority, either one can be popped first. That does not change Dijkstra or normal A* correctness: the important rule is that nothing with a lower priority is waiting. The final route may differ only when there are genuinely equal-cost choices.' },
      { type: 'table', head: ['Word in the app', 'Meaning'], rows: [
        [STATS.explored.label, 'How many intersections were settled before the answer was known.'],
        [STATS.heap.label, 'The largest number of frontier candidates waiting at once.'],
        ['Parent', 'The previous road recorded when a cheaper route to a neighbour was found.'],
      ] },
      { type: 'tryit', scenario: 'step-inspector', label: 'Try stepping through the queue' },
    ],
    tryIt: 'step-inspector',
    related: ['node-inspector', 'why-extra-nodes', 'dijkstra', 'astar'],
  },
  {
    id: 'why-extra-nodes',
    title: 'Why so many extra intersections are checked',
    category: 'How search decides',
    summary: 'The search is proving no cheaper unseen route exists, not only drawing the final road line.',
    questions: [
      'Why are so many unnecessary nodes selected even when that path is not chosen?',
      'When the graph is being calculated, what\'s the criteria to choose a node?',
    ],
    blocks: [
      { type: 'p', html: 'The final route is only the winning chain of parent links. The search cloud is larger because the algorithm must prove that no other route can beat it.' },
      { type: 'diagram', id: 'search-shapes' },
      { type: 'h', text: 'Dijkstra has to prove the answer' },
      { type: 'p', html: `For ${ALGO.dijkstra.name}, every unsettled frontier entry is a possible future route. Until the drop-off is the cheapest remaining entry, there might still be a cheaper path through another intersection.` },
      { type: 'callout', tone: 'why', html: 'That is the proof idea: Dijkstra must settle every intersection cheaper than the drop-off before it can be sure the drop-off route is the fastest. Those checked intersections can be far away from the final yellow route.' },
      { type: 'p', html: 'The blue to violet gradient shows settle order. Early blue intersections were chosen first; later violet intersections were chosen after the queue had grown around the pickup.' },
      { type: 'trace', id: 'dijkstra-demo' },
      { type: 'h', text: 'A* checks less because it has a compass' },
      { type: 'p', html: `${ALGO.astar.name} still keeps the proof, but adds <code>h</code>: an optimistic estimate to the drop-off. That bends the frontier toward the goal, so the trace usually reaches the drop-off after fewer settled intersections than Dijkstra on the same demo graph.` },
      { type: 'trace', id: 'astar-demo' },
      { type: 'p', html: 'Use the trace tables above for the numeric comparison rather than memorising a count: each row is one settled intersection, so fewer rows means less search work on that demo.' },
      { type: 'h', text: 'When pruning goes too far' },
      { type: 'p', html: `${ALGO['astar-overestimate'].name} multiplies the estimate by ${FACTS.overestimateFactor}. That often checks fewer intersections, but the estimate can overpower the real cost so far and miss the truly fastest route.` },
      { type: 'h', text: 'Meeting in the middle' },
      { type: 'p', html: `${ALGO.bidirectional.name} runs a time-ordered search from the pickup and another from the drop-off. It can cover less ground because the two waves meet in the middle, but it runs to completion instead of supporting the Step inspector.` },
      { type: 'table', head: ['Algorithm', 'Why it may check extra intersections'], rows: [
        [ALGO.dijkstra.name, 'Needs to settle everything cheaper than the drop-off.'],
        [ALGO.astar.name, 'Uses a safe estimate, so it still proves optimality but avoids many sideways checks.'],
        [ALGO['astar-overestimate'].name, 'Prunes aggressively; fast search, not always fastest route.'],
        [ALGO.bidirectional.name, 'Splits the proof between two frontiers that meet.'],
      ] },
      { type: 'tryit', scenario: 'step-inspector', label: 'Try the Step view' },
    ],
    tryIt: 'step-inspector',
    related: ['priority-queue', 'node-inspector', 'astar-overestimate', 'bidirectional'],
  },
  {
    id: 'node-inspector',
    title: 'How to use Step and the node inspector',
    category: 'How search decides',
    summary: 'Press Step to settle one intersection and read the “Why this intersection?” panel.',
    questions: ['What does Step do?', 'Why was a node selected?'],
    blocks: [
      { type: 'p', html: 'After placing pickup and drop-off pins, press <kbd>Step</kbd> instead of Find route. Each press advances to the next settled intersection: one real queue decision at a time.' },
      { type: 'callout', tone: 'tip', html: `Step works for ${ALGO.bfs.name}, ${ALGO.dijkstra.name}, ${ALGO.astar.name}, and ${ALGO['astar-overestimate'].name}. ${ALGO.bidirectional.name} does not have a step-by-step view, so it runs instantly and reports final stats.` },
      { type: 'h', text: 'What the panel shows' },
      { type: 'p', html: 'The inspector card is titled <strong>Why this intersection?</strong>. Under it, the app names the selected point, such as the pickup, the drop-off, or an intersection number, then shows the algorithm name and a sentence explaining that algorithm\'s rule.' },
      { type: 'list', items: [
        '<strong>Formula.</strong> Dijkstra shows <code>priority = g</code>; A* shows <code>priority f = g + h</code>; Fast but sloppy shows <code>f = g + 2×h</code>; Fewest turns shows hop priority.',
        '<strong>Table.</strong> The columns are exactly <code>Intersection</code>, <code>Priority</code>, and <code>Why it matters</code>.',
        '<strong>Chosen row.</strong> The first row is the intersection just settled, labelled <code>lowest priority — chosen now</code>.',
        '<strong>Queue rows.</strong> Up to five more rows show the best waiting frontier candidates, labelled <code>waiting in queue</code>.',
      ] },
      { type: 'h', text: 'How to read one Step' },
      { type: 'steps', items: [
        'Look at the chosen row. Its priority is the smallest priority left in the queue at that moment.',
        'Read the formula. For Dijkstra, a smaller travel time from the pickup wins. For A*, a smaller travel time plus estimated time left wins.',
        'Compare the waiting rows. These are the next candidates unless a relaxation inserts an even cheaper entry first.',
        `Watch ${STATS.explored.label}. It increases by one for each Step because one more intersection has become settled.`,
      ] },
      { type: 'p', html: 'Example: if A* chooses an intersection with <code>g = 20s</code> and <code>h = 8s</code>, its priority is <code>28s</code>. A different intersection with <code>g = 18s</code> but <code>h = 20s</code> waits, because <code>38s</code> is worse.' },
      { type: 'callout', tone: 'why', html: 'The footer says every blue intersection was chosen the same way: always the lowest priority left in the queue. Most are not on the final route because they are the proof that nothing faster exists.' },
      { type: 'trace', id: 'astar-demo' },
      { type: 'p', html: 'If you want the rule behind the formula, start with <a data-kb="priority-queue">Why the priority queue chooses that intersection</a>. If you want to know why the coloured search area is wider than the final route, read <a data-kb="why-extra-nodes">Why so many extra intersections are checked</a>.' },
      { type: 'tryit', scenario: 'step-inspector', label: 'Open a Step demo' },
    ],
    tryIt: 'step-inspector',
    related: ['priority-queue', 'why-extra-nodes', 'choose-algorithm'],
  },
];
